### ISSUE TITLE
unordered page on next pagination

### ISSUE THREAD

**Issue by blackinitial** [uasoft-indonesia/badaso-documentation-gen-2#9]
**Describe the bug**
i look on documentation unordered pagination. 
like on 'Apa itu Badaso' page , we must to next page on 'Instalasi' page, but jump to 'Code Editor' page

**Expected behavior**
Fix the pagination with true pagination order

**Comment by dannyatthaya** [comment]
Hi @blackinitial, this issue has been fixed on PR #9.
